apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
      - name: mysql
        image: ft_mysql
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - "sh"
            - "/tmp/livenessprobe.sh"
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASS
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: mysql_root_pass
        - name: MYSQL_WP_DB_NAME
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: mysql_wp_db_name
        - name: MYSQL_WP_USER_NAME
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: mysql_wp_user_name
        - name: MYSQL_WP_USER_PASS
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: mysql_wp_user_pass
