apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: ft_grafana
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - "sh"
            - "/tmp/livenessprobe.sh"
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
        ports:
        - name: grafana
          containerPort: 3000
        env:
        - name: GRAFANA_USER_NAME
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: grafana_user_name
        - name: GRAFANA_USER_PASS
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: grafana_user_pass
        - name: INFLUXDB_USER_NAME
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: influxdb_user_name
        - name: INFLUXDB_USER_PASS
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: influxdb_user_pass
