apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ft_phpmyadmin
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - "sh"
            - "/tmp/livenessprobe.sh"
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
        ports:
        - name: phpmyadmin
          containerPort: 5000
