apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ft_phpmyadmin
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - "sh"
            - "/tmp/livenessprobe.sh"
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
        ports:
        - name: phpmyadmin
          containerPort: 5000
        env:
        - name: PHPMYADMIN_USER_NAME
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: phpmyadmin_user_name
        - name: PHPMYADMIN_USER_PASS
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: phpmyadmin_user_pass
