apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: ft_wordpress
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - "sh"
            - "/tmp/livenessprobe.sh"
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
        ports:
        - containerPort: 5050
          name: wordpress
        env:
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: config-secret
                key: mysql_database_name
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: config-secret
                key: mysql_user_name
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-secret
                key: mysql_user_password
          - name: WORDPRESS_TITLE
            value: ft_services
          - name: WORDPRESS_ADMIN_NAME
            valueFrom:
              secretKeyRef:
                name: config-secret
                key: wordpress_admin_name
          - name: WORDPRESS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-secret
                key: wordpress_admin_password
          - name: WORDPRESS_ADMIN_MAILADDRESS
            valueFrom:
              secretKeyRef:
                name: config-secret
                key: wordpress_admin_mailaddress
          - name: WORDPRESS_USER1_NAME
            valueFrom:
              secretKeyRef:
                name: config-secret
                key: wordpress_user1_name
          - name: WORDPRESS_USER1_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-secret
                key: wordpress_user1_password
          - name: WORDPRESS_USER1_MAILADDRESS
            valueFrom:
              secretKeyRef:
                name: config-secret
                key: wordpress_user1_mailaddress
