apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps-data
    port: 20
    targetPort: 20
    protocol: TCP
  - name: ftps-control
    port: 21
    targetPort: 21
    protocol: TCP
  - name: ftps-passive
    port: 60000
    targetPort: 60000
    protocol: TCP
