apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftps-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/data"
